### ISSUE TITLE
`get_assignments` needs `workspace` argument

### ISSUE THREAD

**Issue by ashwinikalantri** [arthur-shaw/susoapi#12]
The `get_workspace` function needs to have a `workspace` argument. It defaults to primary. Not able to get any assignments from any workspace except the primary.

**Comment by arthur-shaw** [comment]
I'm holding off on updating this function until the GraphQL endpoint offers more information. The dev team is aware of this issue and will hopefully update the GraphQL schema soon. See below what the REST and GraphQL endpoints offer.

REST:

![image](https://user-images.githubusercontent.com/47256431/121352844-41ba3180-c8fb-11eb-8ba9-b5f3488b4d96.png)

GraphQL:

![image](https://user-images.githubusercontent.com/47256431/121352782-30712500-c8fb-11eb-98ad-bf478f2cd42a.png)

**Comment by arthur-shaw** [comment]
Commit 4dae472 closes this issue.
