### ISSUE TITLE
Workspace argument in `set_credentials` function

### ISSUE THREAD

**Issue by ashwinikalantri** [arthur-shaw/susoapi#24]
May I suggest adding a `workspace` argument in the `set_credentials` function. This will reduce the need to set workspace for every function.

I feel that most processes don't work with different workspaces at a time. And even if there is such a scenario, the set workspace can be over-ridden in the function.

**Comment by arthur-shaw** [comment]
This is a great idea! When I updated the package to accommodate workspaces, I thought about this. At the time, I thought it would be better to let users set the workspace for each call. But after "eating my own dogfood" by using my package for a few projects, I think that your recommendation is right: let users set credentials and workspace for their "default" workspace, and make changes to the workspace if they need ot touch other workspaces on their servers.
