### ISSUE TITLE
Unknown error while exporting with susoapi

### ISSUE THREAD

**Issue by emawbgit** [arthur-shaw/susoapi#40]
Dear Arthur,

Following your instructions, I have loaded the credential to the HQ. 
Then, when I follow your steps for exporting the data via API, I get the error below (server authorization issue possibly)?
![image](https://user-images.githubusercontent.com/65594313/231772811-d1f61e6a-142e-4716-b7cb-0ce3f98060e5.png)

I was wondering if you could please help narrow down the problem.

Thanks,
Emanuele (LSMS Team, Rome)

fyi:
1) R has writing permission on my WB machine
2) the GlobalProtect is on (needed for the server to be accessible)

**Comment by arthur-shaw** [comment]
@emawbgit , it's hard to tell from the steps and the screenshot what the problem is.

Let's discuss offline in order to go into more detail. If relevant, I'll update this issue.
